## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false
git:
  depth: 99999999
jobs:
  allow_failures:
    - julia: nightly
